site_name: reQ
site_description: HTTP request library for q language
site_url: http://jmcmurray.co.uk/reQ
repo_url: https://github.com/jonathonmcmurray/reQ
theme:
    name: mkdocs
google_analytics: ['UA-119708613-1', 'jmcmurray.co.uk']

nav:
- Overview: 'index.md'
- Features:
    - 'Cookies': 'features/cookies.md'
    - 'Headers': 'features/headers.md'
    - 'HTTP redirects': 'features/redirects.md'
    - 'Verbose mode': 'features/verbose.md'
- API: 
    - 'Public functions': 'api/md/public.md'
    - 'Private functions': 'api/md/private.md'
    - 'Variables': 'api/md/variable.md'
- Examples:
    - 'Advent of Code': 'examples/aoc.md'
    - 'GitHub': 'examples/github.md'
    - 'JIRA': 'examples/jira.md'
    - 'Zoho': 'examples/zoho.md'
